-----------------------------------------------------------
-- ? 1. Crear tabla (solo si no existe)
-----------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE '
      CREATE TABLE SERIES_RESULTS (
         ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
         CALC_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP,
         VALUE      NUMBER(20)
      )';
EXCEPTION
   WHEN OTHERS THEN
      -- ORA-00955: tabla ya existe
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
/
-----------------------------------------------------------


-----------------------------------------------------------
-- ? 2. Crear o reemplazar procedimiento almacenado
--    (SIN COMMIT para control desde Java)
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_LOG_VALUE (
    p_val IN NUMBER
) AS
BEGIN
    INSERT INTO SERIES_RESULTS (VALUE)
    VALUES (p_val);
    -- ? No se hace COMMIT aquí, porque se maneja desde Java
END;
/
-----------------------------------------------------------


-----------------------------------------------------------
-- ? 3. Verificar si el procedimiento quedó válido
-----------------------------------------------------------

SELECT object_name, status
FROM user_objects
WHERE object_name = UPPER('SP_LOG_VALUE');
/
-----------------------------------------------------------


-----------------------------------------------------------
-- ? 4. (Opcional) Prueba directa del procedimiento
-----------------------------------------------------------

BEGIN
    SP_LOG_VALUE(9999);
END;
/
-----------------------------------------------------------


-----------------------------------------------------------
-- ? 5. Confirmar inserción (solo para validación)
-----------------------------------------------------------

SELECT * FROM SERIES_RESULTS ORDER BY ID DESC;
/
-----------------------------------------------------------