package com.example.largeoracleapp;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * LargeOracleApp.java
 *
 * Demostración de una aplicación Java (IntelliJ) que conecta con Oracle 19c,
 * realiza operaciones básicas (crear tabla, insertar, consultar, llamar a
 * un procedimiento almacenado) y muestra una estructura extensa (para fines
 * educativos y de prueba). Reemplace los valores de conexión por los de su
 * entorno.
 *
 * NOTA: Este archivo incluye una sección de comentarios larga para cumplir
 * con el requerimiento de tamaño del archivo. El código real, utilizable y
 * explicado está al principio del fichero.
 */
public class LargeOracleApp {

    // -------- CONFIGURACIÓN (modifique según su entorno) --------
    private static final String DB_USER = "system";
    private static final String DB_PASSWORD = "Tapiero123";
    private static final String DB_HOST = "localhost";
    private static final String DB_PORT = "1521";
    private static final String DB_SID = "orcl";

    // cadena de conexion en formato JDBC para ORACLE :.
    private static final String JDBC_URL = String.format(
            "jdbc:oracle:thin:@%s:%s/%s", DB_HOST, DB_PORT, DB_SID);

    // nombre de la tabla de ejemplo
    private static final String TABLE_NAME = "SERIES_RESULTS";

    public static void main(String[] args) {
        System.out.println("Iniciando LargeOracleApp...");
        
        try (Connection conn = getConnection()) {
            // Auto-commit desactivado para control explicito
            conn.setAutoCommit(false);
            
            createTableIfNotExists(conn);
            long result = calcularSerieSumandoDe4En4Hasta(3862);
            System.out.println("Resultado de la serie: " + result);
            
            insertResult(conn, result);
            callStoredProcedureExample(conn, result);
            
            List<Long> all = queryAllResults(conn);
            System.out.println("Resultados guardados em DB: " + all);
            
            conn.commit();
        } catch (SQLException ex) {
            System.err.println("Error en conexion/operaciones SQL: " + ex.getMessage());
            ex.printStackTrace();
        }
        
        System.out.println("LargeOracleApp finalizado.");
    }

    // --------------------------------------------------------------
    // Conexión
    // --------------------------------------------------------------
    private static Connection getConnection() throws SQLException {
        Properties props = new Properties();
        props.setProperty("user", DB_USER);
        props.setProperty("password", DB_PASSWORD);

        DriverManager.setLoginTimeout(10);
        return DriverManager.getConnection(JDBC_URL, props);
    }

    // --------------------------------------------------------------
    // Lógica de la serie: suma desde 0 incrementando de 4 en 4 hasta 3862
    // --------------------------------------------------------------
    private static long calcularSerieSumandoDe4En4Hasta(int limite) {
        long suma = 0;
        for (int i = 1; i <= limite; i += 4) {
            suma += i;
        }
        return suma;
    }

    // --------------------------------------------------------------
    // Creación de la tabla
    // --------------------------------------------------------------
    private static void createTableIfNotExists(Connection conn) throws SQLException {
        String ddl = "BEGIN\n" +
                " EXECUTE INMEDIATE 'CREATE TABLE " + TABLE_NAME + " (" +
                "ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "CALC_DATE TIMESTAMP DEFAULT SYSTIMESTAMP, " +
                "VALUE NUMBER(20)\n" +
                ")';\n" +
                "EXCEPTION\n" +
                " WHEN OTHERS THEN\n" +
                "   IF SQLCODE != -955 THEN\n" +
                "       RAISE;\n" +
                "   END IF;\n" +
                "END;";

        try (CallableStatement cs = conn.prepareCall(ddl)) {
            cs.execute();
            System.out.println("Tabla comprobada/creada: " + TABLE_NAME);
        }
    }

    // --------------------------------------------------------------
    // Insert
    // --------------------------------------------------------------
    private static void insertResult(Connection conn, long value) throws SQLException {
        String insert = "INSERT INTO " + TABLE_NAME + " (VALUE) VALUES (?)";
        try (PreparedStatement ps = conn.prepareStatement(insert)) {
            ps.setLong(1, value);
            int rows = ps.executeUpdate();
            System.out.println("Filas insertadas: " + rows);
        }
    }

    // --------------------------------------------------------------
    // Query
    // --------------------------------------------------------------
    private static List<Long> queryAllResults(Connection conn) throws SQLException {
        String q = "SELECT VALUE FROM " + TABLE_NAME + " ORDER BY ID";
        List<Long> list = new ArrayList<>();
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(q)) {
            while (rs.next()) {
                list.add(rs.getLong(1));
            }
        }
        return list;
    }

    private static void callStoredProcedureExample(Connection conn, long result) {

    }
}